name: hawfinch
channels:
- defaults
- teriforey
- conda-forge
dependencies:
- python
- pywps
- sphinx
- jinja2
- pytest
- click
- psutil
- basemap
- pip:
  - git+https://github.com/tommygod3/pyNAMEplot@master#egg=pynameplot
